# Practical No. 5

### Aim:To create 1D,2D,and Multidimensional array

In [3]:
#Name:Rudraksh K. Ramekar
#Roll no.:69
#Subject:ET1
#Sec:C
#Date:19/08/2025

In [1]:
import numpy as np

In [2]:
#creating 1D array using numpy

In [3]:
a1=np.array([10,20,30,40,50])

In [4]:
a1

array([10, 20, 30, 40, 50])

In [5]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [6]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [7]:
#creating 2D array using matrix

In [8]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
